/**
 * Generated by tessera@0.0.0.
 * Asset licenses: unknown
 */
import { Canvas } from '@react-three/fiber'
import { Environment, OrthographicCamera, PerspectiveCamera, useGLTF } from '@react-three/drei'

export type SceneProps = {
  readonly modelUrl?: string
  readonly environmentUrl?: string | null
}

const defaultModelUrl = './scene.glb'
const defaultEnvironmentUrl = null

export function Scene(props: SceneProps) {
  const modelUrl = props.modelUrl ?? defaultModelUrl
  const environmentUrl = props.environmentUrl === undefined ? defaultEnvironmentUrl : props.environmentUrl
  return (
    <Canvas>
      <SceneContent modelUrl={modelUrl} environmentUrl={environmentUrl} />
    </Canvas>
  )
}

function SceneContent(props: { readonly modelUrl: string; readonly environmentUrl: string | null }) {
  const { scene } = useGLTF(props.modelUrl)
  return (
    <>
      <primitive object={scene} />
      {props.environmentUrl ? <Environment files={props.environmentUrl} /> : null}
      <ambientLight
        color={'#ffffff'}
        intensity={0.2}
      />
      <PerspectiveCamera makeDefault fov={50} near={0.1} far={1000} position={[0, 1.6, 4]} />
    </>
  )
}
