/**
 * Generated by tessera@0.0.0.
 * Asset licenses: unknown
 */
import {
  ACESFilmicToneMapping,
  AgXToneMapping,
  AmbientLight,
  Color,
  EquirectangularReflectionMapping,
  Fog,
  FogExp2,
  MathUtils,
  NeutralToneMapping,
  NoToneMapping,
  OrthographicCamera,
  PerspectiveCamera,
  PMREMGenerator,
  RectAreaLight,
  Scene,
} from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { RGBELoader } from 'three/addons/loaders/RGBELoader.js';

const CONFIG = {
  "glbUrl": "./scene.glb",
  "environmentUrl": null,
  "exposure": 1,
  "toneMapping": "neutral",
  "sky": {
    "kind": "none"
  },
  "fog": {
    "kind": "none"
  },
  "ambient": {
    "color": "#ffffff",
    "intensity": 0.2
  },
  "camera": null,
  "areaLights": [],
  "loaders": {
    "ktx2": false,
    "draco": false,
    "meshopt": false
  }
};

const TONE_MAPPING = {
  none: NoToneMapping,
  aces: ACESFilmicToneMapping,
  agx: AgXToneMapping,
  neutral: NeutralToneMapping,
};

/**
 * @param {{ renderer: import('three').WebGLRenderer }} input
 * @returns {Promise<{ scene: import('three').Scene, camera: import('three').Camera, update: () => void }>}
 */
export async function createScene({ renderer }) {
  const scene = new Scene();
  renderer.toneMapping = TONE_MAPPING[CONFIG.toneMapping];
  renderer.toneMappingExposure = CONFIG.exposure;
  scene.add(new AmbientLight(new Color(CONFIG.ambient.color), CONFIG.ambient.intensity));
  await applyEnvironment(scene, renderer);
  applyFog(scene);
  const loader = new GLTFLoader();
  if (CONFIG.loaders.ktx2 || CONFIG.loaders.draco || CONFIG.loaders.meshopt) {
    throw new Error('KTX2, Draco, and meshopt loaders are omitted until those encodings are exported');
  }
  const gltf = await loader.loadAsync(CONFIG.glbUrl);
  scene.add(gltf.scene);
  for (const light of CONFIG.areaLights) {
    const rect = new RectAreaLight(new Color(light.color), light.intensity, light.width, light.height);
    rect.name = light.name;
    rect.position.set(light.position[0], light.position[1], light.position[2]);
    rect.rotation.set(
      MathUtils.degToRad(light.rotation[0]),
      MathUtils.degToRad(light.rotation[1]),
      MathUtils.degToRad(light.rotation[2]),
      'XYZ',
    );
    scene.add(rect);
  }
  const camera = createCamera();
  function update() {}
  return { scene, camera, update };
}

/**
 * @param {import('three').Scene} scene
 * @param {import('three').WebGLRenderer} renderer
 */
async function applyEnvironment(scene, renderer) {
  if (CONFIG.environmentUrl !== null) {
    const texture = await new RGBELoader().loadAsync(CONFIG.environmentUrl);
    texture.mapping = EquirectangularReflectionMapping;
    const pmrem = new PMREMGenerator(renderer);
    scene.environment = pmrem.fromEquirectangular(texture).texture;
    scene.background = scene.environment;
    pmrem.dispose();
    return;
  }
  if (CONFIG.sky.kind === 'color') {
    scene.background = new Color(CONFIG.sky.color);
  }
}

/** @param {import('three').Scene} scene */
function applyFog(scene) {
  if (CONFIG.fog.kind === 'linear') {
    scene.fog = new Fog(new Color(CONFIG.fog.color), CONFIG.fog.near, CONFIG.fog.far);
  }
  if (CONFIG.fog.kind === 'exponential') {
    scene.fog = new FogExp2(new Color(CONFIG.fog.color), CONFIG.fog.density);
  }
}

/** @returns {import('three').Camera} */
function createCamera() {
  if (CONFIG.camera === null) {
    return new PerspectiveCamera(50, 1, 0.1, 1000);
  }
  const spec = CONFIG.camera;
  const camera =
    spec.type === 'orthographic'
      ? new OrthographicCamera(
          -spec.orthoSize * (16 / 9),
          spec.orthoSize * (16 / 9),
          spec.orthoSize,
          -spec.orthoSize,
          spec.near,
          spec.far,
        )
      : new PerspectiveCamera(spec.fov, 1, spec.near, spec.far);
  camera.position.set(spec.position[0], spec.position[1], spec.position[2]);
  camera.rotation.set(
    MathUtils.degToRad(spec.rotation[0]),
    MathUtils.degToRad(spec.rotation[1]),
    MathUtils.degToRad(spec.rotation[2]),
    'XYZ',
  );
  return camera;
}
