import type { Document, Entity, Vec3 } from "@tessera/schema";
import type { Result, TesseraError } from "@tessera/std";
import { abortError, err, ok, tesseraError } from "@tessera/std";
import type { BlobStore } from "@tessera/storage";
import { createGltfExporter } from "./gltf.js";
import { type GltfExportOptions, GltfExportOptionsSchema } from "./options.js";
import { collectExportedEntities } from "./sidecar-build.js";
import type { ExportBundle, Exporter } from "./types.js";

const gltfExporter = createGltfExporter();

type SkyConfig =
  | { readonly kind: "none" }
  | { readonly kind: "color"; readonly color: string }
  | { readonly kind: "environment"; readonly rotation: number; readonly intensity: number };

type FogConfig =
  | { readonly kind: "none" }
  | { readonly kind: "linear"; readonly color: string; readonly near: number; readonly far: number }
  | { readonly kind: "exponential"; readonly color: string; readonly density: number };

interface CameraConfig {
  readonly type: "perspective" | "orthographic";
  readonly fov: number;
  readonly near: number;
  readonly far: number;
  readonly orthoSize: number;
  readonly position: Vec3;
  readonly rotation: Vec3;
}

interface AreaLightConfig {
  readonly name: string;
  readonly color: string;
  readonly intensity: number;
  readonly width: number;
  readonly height: number;
  readonly position: Vec3;
  readonly rotation: Vec3;
}

interface SceneConfig {
  readonly glbUrl: string;
  readonly environmentUrl: string | null;
  readonly exposure: number;
  readonly toneMapping: "neutral" | "aces" | "agx" | "none";
  readonly sky: SkyConfig;
  readonly fog: FogConfig;
  readonly ambient: { readonly color: string; readonly intensity: number };
  readonly camera: CameraConfig | null;
  readonly areaLights: readonly AreaLightConfig[];
  readonly loaders: { readonly ktx2: boolean; readonly draco: boolean; readonly meshopt: boolean };
}

/**
 * Built-in Three.js ESM exporter (`09` §6). Emits `scene.js` plus the glTF bundle.
 *
 * @example
 * ```ts
 * const exporter = createCodeThreeExporter();
 * const bundle = await exporter.export({ document, blobs, options });
 * ```
 *
 * @public
 */
export function createCodeThreeExporter(): Exporter<GltfExportOptions> {
  return {
    id: "code-three",
    displayName: "Three.js module",
    fileExtensions: ["js"],
    optionsSchema: GltfExportOptionsSchema,
    export: exportCodeThree,
  };
}

async function exportCodeThree(
  input: {
    readonly document: Document;
    readonly blobs: BlobStore;
    readonly options: GltfExportOptions;
  },
  signal?: AbortSignal,
): Promise<Result<ExportBundle, TesseraError>> {
  const stopped = cancelled(signal);
  if (stopped !== undefined) {
    return stopped;
  }
  const parsed = GltfExportOptionsSchema.safeParse(input.options);
  if (!parsed.success) {
    return err(tesseraError("INVALID_INPUT", "invalid code-three export options"));
  }
  const options = parsed.data;
  const gltf = await gltfExporter.export(
    { document: input.document, blobs: input.blobs, options },
    signal,
  );
  if (!gltf.ok) {
    return gltf;
  }
  const environmentUrl = hdrUrl(gltf.value.files);
  const source = printSceneJs(input.document, options, environmentUrl);
  const files = [
    ...gltf.value.files,
    { path: "scene.js", blob: new Blob([source], { type: "text/javascript" }) },
  ];
  if (gltf.value.attribution === undefined) {
    return ok({ files, warnings: gltf.value.warnings });
  }
  return ok({
    files,
    warnings: gltf.value.warnings,
    attribution: gltf.value.attribution,
  });
}

function printSceneJs(
  document: Document,
  options: GltfExportOptions,
  environmentUrl: string | null,
): string {
  const config = sceneConfig(document, options, environmentUrl);
  const licenses = licenseSummary(document);
  const header = [
    "/**",
    ` * Generated by ${document.meta.generator}.`,
    ` * Asset licenses: ${licenses}`,
    " */",
  ].join("\n");
  return `${header}
import {
  ACESFilmicToneMapping,
  AgXToneMapping,
  AmbientLight,
  Color,
  EquirectangularReflectionMapping,
  Fog,
  FogExp2,
  MathUtils,
  NeutralToneMapping,
  NoToneMapping,
  OrthographicCamera,
  PerspectiveCamera,
  PMREMGenerator,
  RectAreaLight,
  Scene,
} from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { RGBELoader } from 'three/addons/loaders/RGBELoader.js';

const CONFIG = ${JSON.stringify(config, null, 2)};

const TONE_MAPPING = {
  none: NoToneMapping,
  aces: ACESFilmicToneMapping,
  agx: AgXToneMapping,
  neutral: NeutralToneMapping,
};

/**
 * @param {{ renderer: import('three').WebGLRenderer }} input
 * @returns {Promise<{ scene: import('three').Scene, camera: import('three').Camera, update: () => void }>}
 */
export async function createScene({ renderer }) {
  const scene = new Scene();
  renderer.toneMapping = TONE_MAPPING[CONFIG.toneMapping];
  renderer.toneMappingExposure = CONFIG.exposure;
  scene.add(new AmbientLight(new Color(CONFIG.ambient.color), CONFIG.ambient.intensity));
  await applyEnvironment(scene, renderer);
  applyFog(scene);
  const loader = new GLTFLoader();
  if (CONFIG.loaders.ktx2 || CONFIG.loaders.draco || CONFIG.loaders.meshopt) {
    throw new Error('KTX2, Draco, and meshopt loaders are omitted until those encodings are exported');
  }
  const gltf = await loader.loadAsync(CONFIG.glbUrl);
  scene.add(gltf.scene);
  for (const light of CONFIG.areaLights) {
    const rect = new RectAreaLight(new Color(light.color), light.intensity, light.width, light.height);
    rect.name = light.name;
    rect.position.set(light.position[0], light.position[1], light.position[2]);
    rect.rotation.set(
      MathUtils.degToRad(light.rotation[0]),
      MathUtils.degToRad(light.rotation[1]),
      MathUtils.degToRad(light.rotation[2]),
      'XYZ',
    );
    scene.add(rect);
  }
  const camera = createCamera();
  function update() {}
  return { scene, camera, update };
}

/**
 * @param {import('three').Scene} scene
 * @param {import('three').WebGLRenderer} renderer
 */
async function applyEnvironment(scene, renderer) {
  if (CONFIG.environmentUrl !== null) {
    const texture = await new RGBELoader().loadAsync(CONFIG.environmentUrl);
    texture.mapping = EquirectangularReflectionMapping;
    const pmrem = new PMREMGenerator(renderer);
    scene.environment = pmrem.fromEquirectangular(texture).texture;
    scene.background = scene.environment;
    pmrem.dispose();
    return;
  }
  if (CONFIG.sky.kind === 'color') {
    scene.background = new Color(CONFIG.sky.color);
  }
}

/** @param {import('three').Scene} scene */
function applyFog(scene) {
  if (CONFIG.fog.kind === 'linear') {
    scene.fog = new Fog(new Color(CONFIG.fog.color), CONFIG.fog.near, CONFIG.fog.far);
  }
  if (CONFIG.fog.kind === 'exponential') {
    scene.fog = new FogExp2(new Color(CONFIG.fog.color), CONFIG.fog.density);
  }
}

/** @returns {import('three').Camera} */
function createCamera() {
  if (CONFIG.camera === null) {
    return new PerspectiveCamera(50, 1, 0.1, 1000);
  }
  const spec = CONFIG.camera;
  const camera =
    spec.type === 'orthographic'
      ? new OrthographicCamera(
          -spec.orthoSize * (16 / 9),
          spec.orthoSize * (16 / 9),
          spec.orthoSize,
          -spec.orthoSize,
          spec.near,
          spec.far,
        )
      : new PerspectiveCamera(spec.fov, 1, spec.near, spec.far);
  camera.position.set(spec.position[0], spec.position[1], spec.position[2]);
  camera.rotation.set(
    MathUtils.degToRad(spec.rotation[0]),
    MathUtils.degToRad(spec.rotation[1]),
    MathUtils.degToRad(spec.rotation[2]),
    'XYZ',
  );
  return camera;
}
`;
}

function sceneConfig(
  document: Document,
  options: GltfExportOptions,
  environmentUrl: string | null,
): SceneConfig {
  const extension = options.container === "gltf" ? "gltf" : "glb";
  return {
    glbUrl: `./${options.outputName}.${extension}`,
    environmentUrl,
    exposure: document.environment.exposure,
    toneMapping: document.environment.toneMapping,
    sky: skyConfig(document),
    fog: document.environment.fog,
    ambient: {
      color: document.environment.ambient.color,
      intensity: document.environment.ambient.intensity,
    },
    camera: pickCamera(document, options),
    areaLights: areaLights(document, options),
    loaders: {
      ktx2: options.textures === "ktx2",
      draco: options.compression === "draco",
      meshopt: options.compression === "meshopt",
    },
  };
}

function skyConfig(document: Document): SkyConfig {
  const sky = document.environment.sky;
  if (sky.kind === "color") {
    return { kind: "color", color: sky.color };
  }
  if (sky.kind === "environment") {
    const asset = document.assets[sky.asset];
    if (asset === undefined || asset.kind !== "environment") {
      return { kind: "environment", rotation: 0, intensity: 1 };
    }
    return { kind: "environment", rotation: asset.rotation, intensity: asset.intensity };
  }
  return { kind: "none" };
}

function pickCamera(document: Document, options: GltfExportOptions): CameraConfig | null {
  if (!options.includeCameras) {
    return null;
  }
  const exported = collectExportedEntities(document, options);
  const mainId = document.settings.mainCamera;
  const main = mainId === null ? undefined : document.entities[mainId];
  if (main !== undefined) {
    const config = cameraConfig(main);
    const allowed = exported.some((entity) => entity.id === main.id);
    if (config !== null && allowed) {
      return config;
    }
  }
  for (const entity of exported) {
    const config = cameraConfig(entity);
    if (config !== null) {
      return config;
    }
  }
  return null;
}

function cameraConfig(entity: Entity): CameraConfig | null {
  const camera = entity.components.camera;
  if (camera === undefined) {
    return null;
  }
  const transform = entity.components.transform;
  return {
    type: camera.type,
    fov: camera.fov,
    near: camera.near,
    far: camera.far,
    orthoSize: camera.orthoSize,
    position: transform === undefined ? [0, 0, 0] : transform.position,
    rotation: transform === undefined ? [0, 0, 0] : transform.rotation,
  };
}

function areaLights(document: Document, options: GltfExportOptions): readonly AreaLightConfig[] {
  if (!options.includeLights) {
    return [];
  }
  const lights: AreaLightConfig[] = [];
  for (const entity of collectExportedEntities(document, options)) {
    const light = entity.components.light;
    if (light === undefined || light.type !== "area") {
      continue;
    }
    const transform = entity.components.transform;
    lights.push({
      name: entity.name,
      color: light.color,
      intensity: light.intensity,
      width: light.size[0],
      height: light.size[1],
      position: transform === undefined ? [0, 0, 0] : transform.position,
      rotation: transform === undefined ? [0, 0, 0] : transform.rotation,
    });
  }
  lights.sort((left, right) => (left.name < right.name ? -1 : left.name > right.name ? 1 : 0));
  return lights;
}

function licenseSummary(document: Document): string {
  const licenses = [
    ...new Set(Object.values(document.assets).map((asset) => asset.license)),
  ].sort();
  if (licenses.length === 0) {
    return "none";
  }
  return licenses.join(", ");
}

function hdrUrl(files: ExportBundle["files"]): string | null {
  const hdr = files.find((file) => file.path.endsWith(".environment.hdr"));
  if (hdr === undefined) {
    return null;
  }
  return `./${hdr.path}`;
}

function cancelled(signal?: AbortSignal): Result<never, TesseraError> | undefined {
  if (signal?.aborted) {
    return err(abortError());
  }
  return undefined;
}
