import type { Document, Entity, Vec3 } from "@tessera/schema";
import type { Result, TesseraError } from "@tessera/std";
import { abortError, err, ok, tesseraError } from "@tessera/std";
import type { BlobStore } from "@tessera/storage";
import { createGltfExporter } from "./gltf.js";
import { type GltfExportOptions, GltfExportOptionsSchema } from "./options.js";
import { collectExportedEntities } from "./sidecar-build.js";
import type { ExportBundle, Exporter } from "./types.js";

const gltfExporter = createGltfExporter();

interface CameraConfig {
  readonly type: "perspective" | "orthographic";
  readonly fov: number;
  readonly near: number;
  readonly far: number;
  readonly orthoSize: number;
  readonly position: Vec3;
  readonly rotation: Vec3;
}

interface AreaLightConfig {
  readonly name: string;
  readonly color: string;
  readonly intensity: number;
  readonly width: number;
  readonly height: number;
  readonly position: Vec3;
  readonly rotation: Vec3;
}

/**
 * Built-in React Three Fiber exporter (`09` §6). Emits `Scene.tsx` plus the glTF bundle.
 *
 * @example
 * ```ts
 * const exporter = createCodeR3fExporter();
 * const bundle = await exporter.export({ document, blobs, options });
 * ```
 *
 * @public
 */
export function createCodeR3fExporter(): Exporter<GltfExportOptions> {
  return {
    id: "code-r3f",
    displayName: "React Three Fiber",
    fileExtensions: ["tsx"],
    optionsSchema: GltfExportOptionsSchema,
    export: exportCodeR3f,
  };
}

async function exportCodeR3f(
  input: {
    readonly document: Document;
    readonly blobs: BlobStore;
    readonly options: GltfExportOptions;
  },
  signal?: AbortSignal,
): Promise<Result<ExportBundle, TesseraError>> {
  const stopped = cancelled(signal);
  if (stopped !== undefined) {
    return stopped;
  }
  const parsed = GltfExportOptionsSchema.safeParse(input.options);
  if (!parsed.success) {
    return err(tesseraError("INVALID_INPUT", "invalid code-r3f export options"));
  }
  const options = parsed.data;
  const gltf = await gltfExporter.export(
    { document: input.document, blobs: input.blobs, options },
    signal,
  );
  if (!gltf.ok) {
    return gltf;
  }
  const environmentUrl = hdrUrl(gltf.value.files);
  const source = printSceneTsx(input.document, options, environmentUrl);
  const files = [
    ...gltf.value.files,
    { path: "Scene.tsx", blob: new Blob([source], { type: "text/tsx" }) },
  ];
  if (gltf.value.attribution === undefined) {
    return ok({ files, warnings: gltf.value.warnings });
  }
  return ok({
    files,
    warnings: gltf.value.warnings,
    attribution: gltf.value.attribution,
  });
}

function printSceneTsx(
  document: Document,
  options: GltfExportOptions,
  environmentUrl: string | null,
): string {
  const extension = options.container === "gltf" ? "gltf" : "glb";
  const defaultUrl = `./${options.outputName}.${extension}`;
  const licenses = licenseSummary(document);
  const header = [
    "/**",
    ` * Generated by ${document.meta.generator}.`,
    ` * Asset licenses: ${licenses}`,
    " */",
  ].join("\n");
  const envLiteral = environmentUrl === null ? "null" : `'${environmentUrl}'`;
  return `${header}
import { Canvas } from '@react-three/fiber'
import { Environment, OrthographicCamera, PerspectiveCamera, useGLTF } from '@react-three/drei'

export type SceneProps = {
  readonly modelUrl?: string
  readonly environmentUrl?: string | null
}

const defaultModelUrl = '${defaultUrl}'
const defaultEnvironmentUrl = ${envLiteral}

export function Scene(props: SceneProps) {
  const modelUrl = props.modelUrl ?? defaultModelUrl
  const environmentUrl = props.environmentUrl === undefined ? defaultEnvironmentUrl : props.environmentUrl
  return (
    <Canvas>
      <SceneContent modelUrl={modelUrl} environmentUrl={environmentUrl} />
    </Canvas>
  )
}

function SceneContent(props: { readonly modelUrl: string; readonly environmentUrl: string | null }) {
  const { scene } = useGLTF(props.modelUrl)
  return (
    <>
      <primitive object={scene} />
      {props.environmentUrl ? <Environment files={props.environmentUrl} /> : null}
      <ambientLight
        color={'${document.environment.ambient.color}'}
        intensity={${String(document.environment.ambient.intensity)}}
      />
${bodyLines(document, options)}
    </>
  )
}
`;
}

function bodyLines(document: Document, options: GltfExportOptions): string {
  const lights = printAreaLights(document, options);
  const camera = printCamera(document, options);
  if (lights.length === 0) {
    return camera;
  }
  return `${lights}\n${camera}`;
}

function printAreaLights(document: Document, options: GltfExportOptions): string {
  const lights = areaLights(document, options);
  if (lights.length === 0) {
    return "";
  }
  return lights
    .map((light) => {
      const pos = vec(light.position);
      const rot = rad(light.rotation);
      return `      <rectAreaLight name={'${light.name}'} color={'${light.color}'} intensity={${String(light.intensity)}} width={${String(light.width)}} height={${String(light.height)}} position={${pos}} rotation={${rot}} />`;
    })
    .join("\n");
}

function printCamera(document: Document, options: GltfExportOptions): string {
  const camera = pickCamera(document, options);
  if (camera === null) {
    return "      <PerspectiveCamera makeDefault fov={50} near={0.1} far={1000} position={[0, 1.6, 4]} />";
  }
  const pos = vec(camera.position);
  const rot = rad(camera.rotation);
  if (camera.type === "orthographic") {
    const halfW = camera.orthoSize * (16 / 9);
    return `      <OrthographicCamera makeDefault left={${String(-halfW)}} right={${String(halfW)}} top={${String(camera.orthoSize)}} bottom={${String(-camera.orthoSize)}} near={${String(camera.near)}} far={${String(camera.far)}} position={${pos}} rotation={${rot}} />`;
  }
  return `      <PerspectiveCamera makeDefault fov={${String(camera.fov)}} near={${String(camera.near)}} far={${String(camera.far)}} position={${pos}} rotation={${rot}} />`;
}

function areaLights(document: Document, options: GltfExportOptions): readonly AreaLightConfig[] {
  if (!options.includeLights) {
    return [];
  }
  const lights: AreaLightConfig[] = [];
  for (const entity of collectExportedEntities(document, options)) {
    const light = entity.components.light;
    if (light === undefined || light.type !== "area") {
      continue;
    }
    const transform = entity.components.transform;
    lights.push({
      name: entity.name,
      color: light.color,
      intensity: light.intensity,
      width: light.size[0],
      height: light.size[1],
      position: transform === undefined ? [0, 0, 0] : transform.position,
      rotation: transform === undefined ? [0, 0, 0] : transform.rotation,
    });
  }
  lights.sort((left, right) => (left.name < right.name ? -1 : left.name > right.name ? 1 : 0));
  return lights;
}

function pickCamera(document: Document, options: GltfExportOptions): CameraConfig | null {
  if (!options.includeCameras) {
    return null;
  }
  const exported = collectExportedEntities(document, options);
  const mainId = document.settings.mainCamera;
  const main = mainId === null ? undefined : document.entities[mainId];
  if (main !== undefined) {
    const config = cameraConfig(main);
    if (config !== null && exported.some((entity) => entity.id === main.id)) {
      return config;
    }
  }
  for (const entity of exported) {
    const config = cameraConfig(entity);
    if (config !== null) {
      return config;
    }
  }
  return null;
}

function cameraConfig(entity: Entity): CameraConfig | null {
  const camera = entity.components.camera;
  if (camera === undefined) {
    return null;
  }
  const transform = entity.components.transform;
  return {
    type: camera.type,
    fov: camera.fov,
    near: camera.near,
    far: camera.far,
    orthoSize: camera.orthoSize,
    position: transform === undefined ? [0, 0, 0] : transform.position,
    rotation: transform === undefined ? [0, 0, 0] : transform.rotation,
  };
}

function licenseSummary(document: Document): string {
  const licenses = [
    ...new Set(Object.values(document.assets).map((asset) => asset.license)),
  ].sort();
  if (licenses.length === 0) {
    return "none";
  }
  return licenses.join(", ");
}

function hdrUrl(files: ExportBundle["files"]): string | null {
  const hdr = files.find((file) => file.path.endsWith(".environment.hdr"));
  if (hdr === undefined) {
    return null;
  }
  return `./${hdr.path}`;
}

function vec(value: Vec3): string {
  return `[${value.join(", ")}]`;
}

function rad(value: Vec3): string {
  return `[${deg(value[0])}, ${deg(value[1])}, ${deg(value[2])}]`;
}

function deg(value: number): string {
  return String((value * Math.PI) / 180);
}

function cancelled(signal?: AbortSignal): Result<never, TesseraError> | undefined {
  if (signal?.aborted) {
    return err(abortError());
  }
  return undefined;
}
